loopring:
  link-collector:
    initial-delay-str: 5000
    fixed-rate-str: 60000

  link-processors:
    initial-delay-str: 5000
    fixed-rate-str: 600000

  entity-processors:
    initial-delay-str: 8000
    fixed-rate-str: 5000

  processor-threadpool-max: 6

############# execute peroidically: ###############
  watched-link-seeds:
    - task-name: jinse-links
      source-site-name: jinse
      selector-key: jinse-links
      target-entity: "org.loopring.crawler.models.WatchedLink"
      crawl-method: json
      crawl-type: multiple
      need-update: false
      link-generator-config:
        repeatedCrawlUrls:
          - "https://api.jinse.com/v1/topic/search?search=lrc&page=1&limit=10&is_true=1&get_total=1"
          - "https://api.jinse.com/v1/topic/search?search=eth&page=1&limit=10&is_true=1&get_total=1"
          
    - task-name: gongxiangcj-short-news-links
      source-site-name: "共享财经"
      selector-key: gongxiangcj-short-news
      target-entity: "org.loopring.crawler.models.CnInfo"
      crawl-method: jsoup
      crawl-type: multiple
      need-update: false
      link-generator-config:
        repeated-crawl-urls:
          - "http://www.gongxiangcj.com/short_news"
          
    - task-name: 8btc-short-news-links
      source-site-name: "巴比特"
      selector-key: 8btc-short-news
      target-entity: "org.loopring.crawler.models.CnInfo"
      crawl-method: jsoup
      crawl-type: multiple
      need-update: false
      link-generator-config:
        repeated-crawl-urls:
          - "https://www.8btc.com/flash"

  all-selectors:
    - key: jinse-links
      source-site-name: "金色财经"
      is-root: true
      name: root
      json-path: "$.list"
      children:
        - name: "selectorKey"
          value-type: "constant"
          const-value: "jinse-news"
        - name: "sourceSiteName"
          value-type: "constant"
          const-value: "金色财经"
        - name: "crawlType"
          value-type: "constant"
          const-value: "single"
        - name: "crawlMethod"
          value-type: "constant"
          const-value: "jsoup"
        - name: "targetEntity"
          value-type: "constant"
          const-value: "org.loopring.crawler.models.CnInfo"
        - name: "taskName"
          value-type: "constant"
          const-value: "jinse-news"
        - name: "title"
          json-path: "$.title"
        - name: "url"
          json-path: "$.topic_url"

    - key: jinse-news
      source-site-name: "金色财经"
      is-root: true
      name: root
      value-type: node
      css-selector: "div.js-article"
      children:
        - name: "title"
          value-type: "text"
          css-selector: "div.title h2"
        - name: "author"
          value-type: "text"
          css-selector: "div.article-info a"
        - name: "publishTimeStr"
          value-type: "text"
          css-selector: "div.article-info div.time"
        - name: "content"
          value-type: "article"
          css-selector: "div.js-article-detail"
        - name: "language"
          value-type: "constant"
          const-value: "zh-Hans"
        - name: "tags"
          value-type: "textarray"
          css-selector: "div.tags a"
        - name: "newsCategory"
          value-type: "constant"
          const-value: "information"
        - name: "bullIndex"
          value-type: "constant"
          const-value: 0
        - name: "bearIndex"
          value-type: "constant"
          const-value: 0
        - name: "forwardNum"
          value-type: "constant"
          const-value: 0
          
  ###############################################################################
    - key: gongxiangcj-short-news
      source-site-name: "共享财经"
      is-root: true
      name: root
      value-type: node
      uuid-fields: "url,title"
      css-selector: "div.kx-left-kuai div.kx-left-kuai-new"
      children:
        - name: "title"
          css-selector: "div.kx-left-kuai-new-title"
          value-type: "text"
        - name: "publishTimeStr"
          css-selector: "div.kx-left-kuai-new-date"
          value-type: "text"
        - name: "source"
          value-type: "constant"
          const-value: "共享财经"
        - name: "content"
          css-selector: "div.kx-left-kuai-new-con p"
          value-type: "article"
        - name: "newsCategory"
          value-type: "constant"
          const-value: "flash"
        - name: "bullIndex"
          value-type: "constant"
          const-value: 0
        - name: "bearIndex"
          value-type: "constant"
          const-value: 0
        - name: "forwardNum"
          value-type: "constant"
          const-value: 0
        - name: "language"
          value-type: "constant"
          const-value: "zh-Hans"
          
   ###############################################################################
    - key: 8btc-short-news
      source-site-name: "巴比特"
      is-root: true
      name: root
      value-type: node
      uuid-fields: "url,title"
      css-selector: "ul.flash-list li"
      children:
        - name: "title"
          css-selector: "div.flash-item__body a span"
          value-type: "text"
        - name: "source"
          css-selector: "div.operate-box.bbt-clearfix span a"
          value-type: "text"
        - name: "content"
          css-selector: "div.flash-item__body div"
          value-type: "article"
        - name: "newsCategory"
          value-type: "constant"
          const-value: "flash"
        - name: "bullIndex"
          value-type: "constant"
          const-value: 0
        - name: "bearIndex"
          value-type: "constant"
          const-value: 0
        - name: "forwardNum"
          value-type: "constant"
          const-value: 0
        - name: "language"
          value-type: "constant"
          const-value: "zh-Hans"



  link-tasks:
    - "jinse-links"
    
  entity-tasks:
    - "8btc-short-news-links"
    - "gongxiangcj-short-news-links"
    - "jinse-news"
